### ISSUE TITLE
Append custom nodes

### ISSUE THREAD

**Issue by guillem-catala** [algrx/algorithmx#1]
Awesome library!

I see in documentation that only few shapes are allowed, but It is there any way to append other elements inside the shape?

**Comment by alexsocha** [comment]
Thanks for the feedback! While it's possible to use [svgattr](https://algrx.github.io/api/NodeSelection/svgattr/) for custom svg attributes, there isn't any direct way to append custom svg elements.

It should be possible to modify the svg after it has rendered with a library like D3, assuming you have control over the JS side. Otherwise, a feature like `svgelem` (which takes in an svg string) might be worth considering.

The reason that only a few shapes are allowed is because getting directed edges to render correctly (just touching the border) is difficult for anything other than a circle.
